In [2]:
import torch as t
a = t.arange(12).view(3,4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
a[t.tensor([1, 2]), t.tensor([0, 2])]

tensor([ 4, 10])

In [7]:
a[t.tensor([1,2])[None,:], t.tensor([0, 2])[:,None]] # 不相同形状的index索引，满足广播法则
                                                     # 获取索引为[1,0]、[2,0]、[1,2]、[2,2]的元素

tensor([[ 4,  8],
        [ 6, 10]])

In [12]:
t.tensor([1,2])[None,:], t.tensor([0, 2])[:,None]   #先广播法则扩展，再索引

(tensor([[1, 2]]),
 tensor([[0],
         [2]]))

In [13]:
print(a[[2,0]])

tensor([[ 8,  9, 10, 11],
        [ 0,  1,  2,  3]])


In [15]:
print(a[[1, 2, 0], [3, 2, 1]])

tensor([ 7, 10,  1])


In [17]:
b = t.tensor([[1, -3, 2], [2, 9, -1], [-8, 4, 1]])
print(b)
b[b > 0] *= 2
print(b)

tensor([[ 1, -3,  2],
        [ 2,  9, -1],
        [-8,  4,  1]])
tensor([[ 2, -3,  4],
        [ 4, 18, -1],
        [-8,  8,  2]])


In [14]:
# 随机生成一组形状为(5,3,4)、0~9数字组成的张量
a = t.randint(1, 10, (5,3,4))
# 获取输出的unique list和索引
output, inverse_indices = t.unique(a, return_inverse=True)
print(output)
print(inverse_indices)
# 通过整数数组索引 还原原始tensor
a_generate = output[inverse_indices]
a_generate.equal(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 3, 3, 5],
         [5, 4, 5, 1],
         [4, 5, 2, 5]],

        [[6, 8, 0, 1],
         [3, 8, 1, 8],
         [1, 4, 6, 5]],

        [[3, 1, 4, 3],
         [5, 7, 5, 6],
         [7, 6, 1, 4]],

        [[3, 2, 5, 4],
         [6, 7, 8, 2],
         [4, 0, 8, 3]],

        [[2, 5, 4, 5],
         [4, 6, 3, 6],
         [4, 4, 8, 1]]])


True

In [23]:
x = t.randint(1, 10, (1,7))
print(x)
x[:,t.tensor([3,4,1,2])]  #  整数数组索引，输出的size等于索引的size，可以大于x本身的size

tensor([[4, 2, 1, 9, 3, 4, 7]])


tensor([[9, 3, 2, 1]])

# nn.embedding学习

In [11]:
import torch
import torch.nn as nn


# 输入
x = torch.LongTensor([[1, 2], [4, 2],[4, 1],[3, 2]])
print(x.shape)
print(x)

print("----------------------------------------------------------------------")
# 调用nn.Embedding函数
# 一共5个词，每个词的词向量维度设置为6维
embeddings = nn.Embedding(5, 6, padding_idx=4)
print(embeddings(x).shape)
print(embeddings(x))

torch.Size([4, 2])
tensor([[1, 2],
        [4, 2],
        [4, 1],
        [3, 2]])
----------------------------------------------------------------------
torch.Size([4, 2, 6])
tensor([[[-0.4663,  0.5425,  0.0533, -1.5261,  0.3110,  0.1871],
         [-1.0019, -1.4731,  0.5315, -0.0386,  2.1083,  0.2508]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-1.0019, -1.4731,  0.5315, -0.0386,  2.1083,  0.2508]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.4663,  0.5425,  0.0533, -1.5261,  0.3110,  0.1871]],

        [[ 2.3033, -0.0814, -0.1821, -1.6813, -1.2886, -0.6068],
         [-1.0019, -1.4731,  0.5315, -0.0386,  2.1083,  0.2508]]],
       grad_fn=<EmbeddingBackward>)


In [6]:
import torch
import torch.nn as nn

x = torch.LongTensor([[1, 2,4,5], [4,2,3,5]])
print(x.shape)
print(x)
print("----------------------------------------------------------------------")
embeddings = nn.Embedding(6, 8, padding_idx=4,max_norm=2)
emb = embeddings(x)
print(emb.shape)
print(emb)
torch.norm(emb,dim=-1)

torch.Size([2, 4])
tensor([[1, 2, 4, 5],
        [4, 2, 3, 5]])
----------------------------------------------------------------------
torch.Size([2, 4, 8])
tensor([[[ 0.9314,  0.5311,  0.6459, -1.2578,  0.4871,  0.4457, -0.1483,
           0.6271],
         [-0.8089,  0.7538, -0.1759, -0.3989, -0.9927,  0.5860,  0.4551,
           1.0254],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000],
         [ 0.1241, -1.4762,  0.5173, -0.5091, -0.8977,  0.3745, -0.1958,
          -0.5423]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000],
         [-0.8089,  0.7538, -0.1759, -0.3989, -0.9927,  0.5860,  0.4551,
           1.0254],
         [-0.2314, -0.7900,  0.3709, -0.9600, -0.1549,  0.9504, -0.5565,
           1.0131],
         [ 0.1241, -1.4762,  0.5173, -0.5091, -0.8977,  0.3745, -0.1958,
          -0.5423]]], grad_fn=<EmbeddingBackward>)


tensor([[2.0000, 2.0000, 0.0000, 2.0000],
        [0.0000, 2.0000, 2.0000, 2.0000]], grad_fn=<CopyBackwards>)

In [7]:
# max_norm 不仅改变输出，还改变embedding矩阵本身的值
embeddings.weight

Parameter containing:
tensor([[-0.0861, -0.4704,  0.6897,  0.6285, -0.0637, -0.4674, -1.5227, -2.5396],
        [ 0.9314,  0.5311,  0.6459, -1.2578,  0.4871,  0.4457, -0.1483,  0.6271],
        [-0.8089,  0.7538, -0.1759, -0.3989, -0.9927,  0.5860,  0.4551,  1.0254],
        [-0.2314, -0.7900,  0.3709, -0.9600, -0.1549,  0.9504, -0.5565,  1.0131],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1241, -1.4762,  0.5173, -0.5091, -0.8977,  0.3745, -0.1958, -0.5423]],
       requires_grad=True)

# BCELoss()学习

In [12]:
import torch
import torch.nn as nn

m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(8, requires_grad=True)
target = torch.empty(8).random_(2)
output = loss(m(input), target)
print(output)
print(output.item())    #item()取出对应位置元素的值

#only one element tensors can be converted to Python scalars

tensor(0.6702, grad_fn=<BinaryCrossEntropyBackward>)
0.6702415347099304


In [13]:
def validate_loss(output, target, weight=None, pos_weight=None):
    # 处理正负样本不均衡问题
    if pos_weight is None:
        label_size = output.size()[1]
        pos_weight = torch.ones(label_size)
    # 处理多标签不平衡问题
    if weight is None:
        label_size = output.size()[1]
        weight = torch.ones(label_size)

    val = 0
    
    #两层循环是为了处理多标签二分类问题
    """
    什么是多标签分类？比如说给一篇文章分配话题，它既可以是科技类又可以是教育类，科技和教育就是这篇文章的两个标签。
    又比如判断一幅图中包含什么，它可能既包含房子又包含马路。房子和马路就是这幅图对应的两个标签。
    将每一种标签，看作是二分类。一个输入样本对应于多个标签，每个标签对应一个二分类（是或不是）。

    """
    for li_x, li_y in zip(output, target):          
        #print(li_x)
        #print(li_y)
        for i, xy in enumerate(zip(li_x, li_y)):
            x, y = xy
            loss_val = pos_weight[i] * y * math.log(x, math.e) + (1 - y) * math.log(1 - x, math.e)
            val += weight[i] * loss_val
    return -val / (output.size()[0] * output.size(1))

import torch
import torch.nn.functional as F
import torch.nn as nn
import math

# 单标签二分类
m = nn.Sigmoid()
weight = torch.tensor([0.8])
loss_fct = nn.BCELoss(reduction="mean", weight=weight)
input_src = torch.Tensor([[0.8], [0.9], [0.3]])
target = torch.Tensor([[1], [1], [0]])
print(input_src.size())
print(target.size())
output = m(input_src)

#print(list(zip(output, target)))
loss = loss_fct(output, target)
print(loss.item())

# 验证计算
validate = validate_loss(output, target, weight)
print(validate.item())

torch.Size([3, 1])
torch.Size([3, 1])
0.4177626371383667
0.4177626371383667


In [14]:
# 单标签二分类
weight = torch.tensor([0.8])
input_src = torch.Tensor([[0.8], [0.9], [0.3]])
target = torch.Tensor([[1], [1], [0]])
print(input_src.size())
print(target.size())
output = torch.sigmoid(input_src)
loss = F.binary_cross_entropy(output, target, weight=weight, reduction='mean')
print(loss.item())

# 验证计算
validate = validate_loss(output, target, weight)
print(validate.item())

torch.Size([3, 1])
torch.Size([3, 1])
0.4177626371383667
0.4177626371383667


###  PyTorch  matmul和mm和bmm区别

从官方文档可以看出:

mm只能进行矩阵乘法,也就是输入的两个tensor维度只能是( n × m ) 和( m × p )

bmm是两个三维张量相乘, 两个输入tensor维度是( b × n × m )和( b × m × p ) , 第一维b代表batch size，输出为( b × n × p )

matmul可以进行张量乘法, 输入可以是高维.

参考链接： https://blog.csdn.net/leo_95/article/details/89946318?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-89946318-blog-100302375.pc_relevant_3mothn_strategy_and_data_recovery&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-89946318-blog-100302375.pc_relevant_3mothn_strategy_and_data_recovery&utm_relevant_index=2

# F.cross_entropy

https://blog.csdn.net/wuliBob/article/details/104119616

In [1]:
 # Example of target with class indices
import torch
import torch.nn.functional as F
#target = torch.randint(5, (3,), dtype=torch.int64)
#print(target)
input = torch.randn(5, 5, requires_grad=True)
print(input)
target1 = torch.arange(len(input)).long()
print(target1)
target2 = torch.zeros(input.size())
target2.fill_diagonal_(1)  
print(target2)
loss1 = F.cross_entropy(input, target1)
loss2 = -torch.sum(F.log_softmax(input, dim=1)*target2,dim=1).mean()
print(loss1)
print(loss2)

tensor([[-0.9925, -0.1532,  0.1798, -0.2197,  0.1275],
        [ 0.2781, -0.7569,  0.9992, -0.1838,  0.8807],
        [ 0.5996, -1.7561,  0.2341, -1.8940, -0.6472],
        [-1.1586,  0.7348, -1.7754, -0.4019, -1.2543],
        [ 1.6600,  2.2298,  0.1292, -0.6996,  1.2672]], requires_grad=True)
tensor([0, 1, 2, 3, 4])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor(1.9565, grad_fn=<NllLossBackward0>)
tensor(1.9565, grad_fn=<NegBackward0>)


In [2]:
# Example of target with class probabilities
import torch
import torch.nn.functional as F
#target = torch.randint(5, (3,), dtype=torch.int64)
#print(target)
input = torch.randn(5, 5, requires_grad=True)
print(input)
target1 = torch.randn(5, 5, requires_grad=True).softmax(dim=1)
print(target1)
target2 = target1  
print(target2)
loss1 = F.cross_entropy(input, target1)
loss2 = -torch.sum(F.log_softmax(input, dim=1)*target2,dim=1).mean()
print(loss1)
print(loss2)

tensor([[ 0.5063, -0.8038,  1.4741,  0.3065,  0.2809],
        [ 0.2667, -0.2912, -1.9044, -0.8381, -1.3603],
        [-0.4387, -0.6134,  1.1705, -0.3995, -0.2180],
        [ 0.2574, -1.7231, -1.5837, -0.8294,  0.3638],
        [-0.0844,  0.4810,  0.3797, -0.1697,  2.2222]], requires_grad=True)
tensor([[0.0775, 0.1946, 0.0979, 0.3984, 0.2317],
        [0.6843, 0.0433, 0.1948, 0.0341, 0.0435],
        [0.1367, 0.1810, 0.2416, 0.2320, 0.2086],
        [0.3044, 0.0080, 0.0401, 0.4427, 0.2047],
        [0.0807, 0.5314, 0.1309, 0.1487, 0.1083]], grad_fn=<SoftmaxBackward0>)
tensor([[0.0775, 0.1946, 0.0979, 0.3984, 0.2317],
        [0.6843, 0.0433, 0.1948, 0.0341, 0.0435],
        [0.1367, 0.1810, 0.2416, 0.2320, 0.2086],
        [0.3044, 0.0080, 0.0401, 0.4427, 0.2047],
        [0.0807, 0.5314, 0.1309, 0.1487, 0.1083]], grad_fn=<SoftmaxBackward0>)
tensor(1.7678, grad_fn=<DivBackward1>)
tensor(1.7678, grad_fn=<NegBackward0>)


# device数据流动

In [4]:
import torch
device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = torch.tensor([1,2,3,4])

In [5]:
x.to(device)

tensor([1, 2, 3, 4], device='cuda:0')

In [6]:
x.device

device(type='cpu')

In [12]:
a=torch.tensor(4)
b=torch.tensor(5)
c=torch.tensor(6)

In [13]:
dict1 ={'a':a,"b":b,"c":c}

In [14]:
dict1

{'a': tensor(4), 'b': tensor(5), 'c': tensor(6)}

In [26]:
dict2 = {k: v.to(device) for k, v in dict1.items()}
dict2

{'a': tensor(4, device='cuda:0'),
 'b': tensor(5, device='cuda:0'),
 'c': tensor(6, device='cuda:0')}

In [22]:
a.device

device(type='cpu')

In [25]:
dict2['a'].device

device(type='cuda', index=0)