In [1]:
x = 3
print(x)
print(id(x))

3
140723577956304


In [2]:
x += 2
print(x)
print(id(x))

5
140723577956368


In [3]:
y = x
print(y)
print(id(y))

5
140723577956368


In [4]:
m = 1
print(id(m))
m = 2
print(id(m))
n = m
print(id(n))

140723577956240
140723577956272
140723577956272


In [7]:
s1 = "{} {} {}".format("myf","isee",3.14)
print(s1)

myf isee 3.14


In [9]:
s2 = '%s %s %f' %("myf","isee",3,14)
print(s2)                       #尚未解决

TypeError: not all arguments converted during string formatting

In [11]:
for ch in "myf isee":
    print(ch,end=" ")

m y f   i s e e 

### python 容器对象

list tuple dict set

In [5]:
a = [1,3,14,"myf",[1,2]]
print(a)
print(type(a))

[1, 3, 14, 'myf', [1, 2]]
<class 'list'>


In [6]:
print(id(a))
a[2:4]=[7,9]   #与之前变量对象的特性作比较
print(id(a))   #修改list的元素，不改变对象id

a = [1,2]
print(id(a))   #修改整个list，与之前得到对象一样，变成新的对象，改变它的id

2447933784960
2447933784960
2447933593216


In [7]:
b1=a
print(id(b1))
b2=a[:]
print(id(b2))

2447933593216
2447933784960


In [8]:
alist = [e**2  for e in[1,2,3,4]]
print(alist)

[1, 4, 9, 16]


In [9]:
alist = [x**2 for x in[1,2,3,4,5,6] if x%2==0]
print(alist)

[4, 16, 36]


In [10]:
#列表的一个性质
print([1,2,3])
print(*[1,2,3])  # “*”引用列表中的元素

[1, 2, 3]
1 2 3


range(n)迭代器对象

### typle 元组
基本与list相同，除了两点

1.[ ]变为（ ）
2.不可修改

In [11]:
nums = [x  for x in range(6)]
print(type(nums))     #是列表类型

<class 'list'>


In [12]:
nums = (x  for x in range(6))
print(type(nums))     #不是元组类型，而是生成器类型

<class 'generator'>


在下面这种应用场景中，一般更适合用生成器类型，它始终是用到一个产生一个，存储空间相比lsit类型小很多，这也是迭代器、生成器的设计目的之一

for e in nums:

   print(e,end=" ")   

In [13]:
nums = (x  for x in range(8))
for e in nums:
    print(e,end=" ")   

0 1 2 3 4 5 6 7 

### 局部变量&全局变量

In [14]:
global_x = 5
a = [1,2,3]
def f(x,y):
    x = 6
    y[0] = 8
    print(x,y)
    return x,y
f(global_x,a)  
print(global_x,a)   #基本类型与非基本类型在局部变量&全局变量上性质的不同
                    #基本类型参数传递的是复制对象，而非基本类型参数传递的是引用

6 [8, 2, 3]
5 [8, 2, 3]


### 类和对象

In [2]:
import torch
x = torch.tensor([1,2,3,4])
print(x,x.type())

tensor([1, 2, 3, 4]) torch.LongTensor


In [7]:
y = torch.exp(x)
p = y.sum(0,keepdim = True)
print(p)
z = y/p
print(z)

tensor(84.7910)
tensor([0.0321, 0.0871, 0.2369, 0.6439])


In [3]:
import numpy as np
myf = np.random.random((3,2))
print (myf)

[[0.57669919 0.02517487]
 [0.52697763 0.06924344]
 [0.437614   0.43994461]]


In [5]:
myf[:2,1:2]

array([[0.02517487],
       [0.06924344]])

### Python格式化输出：f-string格式化输出

f-string简介
python3.6引入了一种新的字符串格式化方式：f-tring格式化字符串。从%s格式化到format格式化再到f-string格式化，格式化的方式越来越直观，f-string的效率也较前两个高一些，使用起来也比前两个简单一些。
同时值得注意的是，f-string就是在format格式化的基础之上做了一些变动，核心使用思想和format一样

### Bert

In [1]:
import math
import re
from random import *
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
text = (
        'Hello, how are you? I am Romeo.\n'
        'Hello, Romeo My name is Juliet. Nice to meet you.\n'
        'Nice meet you too. How are you today?\n'
        'Great. My baseball team won the competition.\n'
        'Oh Congratulations, Juliet\n'
        'Thanks you Romeo'
    )
sentences = re.sub("[.,!?\\-]", '', text.lower()).split('\n')  # filter '.', ',', '?', '!'
word_list = list(set(" ".join(sentences).split()))
word_dict = {'[PAD]': 0, '[CLS]': 1, '[SEP]': 2, '[MASK]': 3}

for i, w in enumerate(word_list):
     word_dict[w] = i + 4
number_dict = {i: w for i, w in enumerate(word_dict)}
vocab_size = len(word_dict)

token_list = list()
for sentence in sentences:
    arr = [word_dict[s] for s in sentence.split()]
    token_list.append(arr)

In [ ]:
text

In [10]:
sentences

['hello how are you i am romeo',
 'hello romeo my name is juliet nice to meet you',
 'nice meet you too how are you today',
 'great my baseball team won the competition',
 'oh congratulations juliet',
 'thanks you romeo']

In [11]:
word_list

['too',
 'are',
 'romeo',
 'how',
 'baseball',
 'you',
 'thanks',
 'i',
 'is',
 'nice',
 'congratulations',
 'hello',
 'the',
 'juliet',
 'great',
 'my',
 'to',
 'won',
 'name',
 'meet',
 'am',
 'oh',
 'today',
 'team',
 'competition']

In [12]:
token_list

[[15, 7, 5, 9, 11, 24, 6],
 [15, 6, 19, 22, 12, 17, 13, 20, 23, 9],
 [13, 23, 9, 4, 7, 5, 9, 26],
 [18, 19, 8, 27, 21, 16, 28],
 [25, 14, 17],
 [10, 9, 6]]

### Filter函数
filter() 函数用于过滤序列，过滤掉不符合条件的元素，返回由符合条件元素组成的新列表。
该接收两个参数，第一个为函数，第二个为序列，序列的每个元素作为参数传递给函数进行判断，然后返回 True 或 False，最后将返回 True 的元素放到新列表中。
注意: Python2.7 返回列表，Python3.x 返回迭代器对象，具体内容可以查看：Python3 filter() 函数

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim

myf = []
list1 = ['A','B','C','H']
list2 = ['A','B','E','F']
#方式一
for Y in filter(lambda x :x not in list1,list2):  #filter()返回的是迭代器
    myf.append(Y)
print(myf)

#方式二
s1=list(filter(lambda x :x in list1,list2))
print(s1)

['E', 'F']
['A', 'B']


### map函数
map()是 Python 内置的高阶函数，它接收一个函数 f 和一个 list，并通过把函数 f 依次作用在 list 的每个元素上，得到一个新的 list 并返回。
有一个点要注意：map函数要经过list转换，即：list(map(function,list1[]))

In [3]:
def F(x):
    return x+2

Y= list(map(F,[1,2,3,4,5,6]))
print(Y)

[3, 4, 5, 6, 7, 8]


### lambda函数
匿名函数lambda：是指一类无需定义标识符（函数名）的函数或子程序。lambda 函数可以接收任意多个参数 (包括可选参数) 并且返回单个表达式的

语法：
`lambda [arg1 [,arg2,.....argn]]:expression`冒号前是参数，可以有多个，用逗号隔开，冒号右边的为表达式（只能为一个）。

**其实lambda返回值是一个函数的地址，也就是函数对象**

In [5]:
print(list(filter(lambda x: x%2,range(10))))    #[1, 3, 5, 7, 9]

[1, 3, 5, 7, 9]


### id(）函数
id() 函数返回对象的唯一标识符，标识符是一个整数。

eg: `id([object])`

参数说明：object -- 对象。

In [4]:
a = 'runoob'
print(id(a))

2487233510512


In [7]:
import collections
print("regular dictionary:\n")
d={}
d['a']='A'
d['b']='C'
d['c']='B'
for k,v in d.items():
    print(k,v)


regular dictionary:

a A
b C
c B


In [8]:
print('Regular dictionary:')
d2={}
d2['a']='A'
d2['b']='B'
d2['c']='C'

d3={}
d3['c']='C'
d3['a']='A'
d3['b']='B' 
print(d2==d3)

print('OrderedDict:')
d4=collections.OrderedDict()
d4['a']='A'
d4['b']='B'
d4['c']='C'
 
d5=collections.OrderedDict()
d5['c']='C'
d5['a']='A'
d5['b']='B'
print(d4==d5)


Regular dictionary:
True
OrderedDict:
False


In [11]:
import torch.nn as nn
blk = []
for i in range(5):
   blk.append(nn.Conv2d(10, 10, 1, 2, bias=False))
print(blk)

model = nn.Sequential(*blk)
print(model)

[Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False), Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False), Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False), Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False), Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False)]
Sequential(
  (0): Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False)
  (1): Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False)
  (2): Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False)
  (3): Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False)
  (4): Conv2d(10, 10, kernel_size=(1, 1), stride=(2, 2), bias=False)
)


# Python zip() 函数

描述：
zip() 函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的列表。

如果各个迭代器的元素个数不一致，则返回列表长度与最短的对象相同，利用 * 号操作符，可以将元组解压为列表。

In [12]:
a = [1,2,3]
b = [4,5,6]
c = [4,5,6,7,8]
zipped = zip(a,b)     # 返回一个对象
zipped

In [14]:
#  zip 方法在 Python 2 和 Python 3 中的不同：
#  在 Python 3.x 中为了减少内存，zip() 返回的是一个对象。如需展示列表，需手动 list() 转换。

list(zipped)  # list() 转换为列表
print(list(zip(a,c)))           # 元素个数与最短的列表一致

a1, a2 = zip(*zip(a,b))          # 与 zip 相反，zip(*) 可理解为解压，返回二维矩阵式
print(list(a1))
print(list(a2))

[(1, 4), (2, 5), (3, 6)]
[1, 2, 3]
[4, 5, 6]


### 赋值、浅拷贝、深拷贝

直接赋值：其实就是对象的引用（别名）。
b = a: 赋值引用，a 和 b 都指向同一个对象。


浅拷贝(copy)：拷贝父对象，不会拷贝对象的内部的子对象。
b = a.copy(): a 和 b 是一个独立的对象，但他们的子对象还是指向统一对象（是引用）。


深拷贝(deepcopy)： copy 模块的 deepcopy 方法，完全拷贝了父对象及其子对象。
b = copy.deepcopy(a): 深度拷贝, a 和 b 完全拷贝了父对象及其子对象，两者是完全独立的。

In [1]:
import copy
a = [1, 2, 3, 4, ['a', 'b']] #原始对象
 
b = a                       #赋值，传对象的引用
c = copy.copy(a)            #对象拷贝，浅拷贝
d = copy.deepcopy(a)        #对象拷贝，深拷贝
 
a.append(5)                 #修改对象a
a[4].append('c')            #修改对象a中的['a', 'b']数组对象
 
print( 'a = ', a )
print( 'b = ', b )
print( 'c = ', c )
print( 'd = ', d )

a =  [1, 2, 3, 4, ['a', 'b', 'c'], 5]
b =  [1, 2, 3, 4, ['a', 'b', 'c'], 5]
c =  [1, 2, 3, 4, ['a', 'b', 'c']]
d =  [1, 2, 3, 4, ['a', 'b']]
