### 1. Basic autograd example 1    

In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms





# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


### 2. Basic autograd example 2

In [2]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

w:  Parameter containing:
tensor([[-0.1872,  0.2175, -0.2642],
        [-0.0606,  0.2910, -0.1240]], requires_grad=True)
b:  Parameter containing:
tensor([0.4170, 0.5223], requires_grad=True)
loss:  1.2155340909957886
dL/dw:  tensor([[ 0.2558, -0.0981, -0.1413],
        [-0.3272,  0.6292,  0.7449]])
dL/db:  tensor([0.3884, 0.9244])
loss after 1 step optimization:  1.1941088438034058


In [38]:
import numpy as np
X = np.random.random((2,11))
Y = np.random.random((4,11))

In [21]:
def cal_dists_one_loop(X,Y):

    num_test = X.shape[0]
    num_train = Y.shape[0]
    dists = np.zeros((num_test, num_train))
    for i in range(num_test):
            dists[i] = np.sqrt(np.sum(np.square(Y - X[i]), axis=1))
            print(dists[i].shape)

    return dists

result = cal_dists_one_loop(myf,lhs)
print(result)

(4,)
(4,)
[[1.34570183 1.16486586 1.2125168  0.98136376]
 [1.40205083 0.96673394 1.51230846 1.36062458]]


In [22]:
x = np.random.random((1,22))
print(x.shape,x[0].shape)

(1, 22) (22,)


In [28]:
d1 = np.multiply(np.dot(X, Y.T), -2)    # shape (num_test, num_train)
d2 = np.sum(np.square(X), axis=1, keepdims=True)    # shape (num_test, 1)
d3 = np.sum(np.square(Y), axis=1)    # shape (1, num_train)

In [35]:
d2.shape

(2, 1)

In [36]:
d3.shape

(4,)

In [49]:
myf = np.array([[1,5,4],[2,3,4]])

In [50]:
myf

array([[1, 5, 4],
       [2, 3, 4]])